import os, sys
from astropy.cosmology import FlatLambdaCDM


DEFAULT_H0 = 67.9
DEFAULT_OM0 = 0.3065
DEFAULT_COSMOLOGY = FlatLambdaCDM(H0=DEFAULT_H0, Om0=DEFAULT_OM0)
# DEFAULT_SKY_AREA_LOW = 1e2
# DEFAULT_SKY_AREA_HIGH = 1e4
# DEFAULT_LUMDIST_RELERR = 0.1
DEFAULT_N_POSTERIOR_SAMPLES = int(5e4)
DEFAULT_N_CPU = 1
DEFAULT_POSTERIOR_OUTDIR = os.path.join(sys.path[0], "output/default_posteriors")

RCOM_SCALE = 10